# Generated by Django 2.0.7 on 2018-08-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
